name: Deploy and Run
env:
 REPO_NAME: ${{github.event.repository.name}}
on:
 push:
   branches:
     - main  # Cambia a la rama deseada si no es 'main'
 workflow_dispatch:
permissions:
 id-token: write
 contents: read
 packages: write
jobs:
 build:
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
    
   - name: Login to Azure Container Registry
     uses: azure/docker-login@v1
     with:
       login-server: ${{ secrets.ACR_NAME_URL }}
       username: ${{ secrets.REGISTRY_USERNAME }}
       password: ${{ secrets.REGISTRY_PASSWORD }}
   
   - name: Build and Push Docker Image
     run: |
           docker build -f ./user_ms/Dockerfile -t ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:${{ github.sha }} ./user_ms
           docker push ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:${{ github.sha }}
       
 deploy:
   needs: build
   runs-on: ubuntu-latest
   environment: test  # Ajusta si tienes variables en entornos específicos
   defaults:
     run:
       shell: bash
   steps:
   - name: Login to Azure
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
   
   - name: Deploy Container Instance
     uses: azure/aci-deploy@v1
     with:
       resource-group: ${{ secrets.RESOURCE_GROUP }}
       location: eastus
       name: user-ms
       image: ${{ secrets.ACR_NAME_URL }}/${{ env.REPO_NAME }}:${{ github.sha}}
       dns-name-label: user-ms-${{ github.run_id }}-${{ github.run_attempt }}
       registry-username: ${{ secrets.REGISTRY_USERNAME }}
       registry-password: ${{ secrets.REGISTRY_PASSWORD }}
       ports: 5000
       cpu: 1
       memory: 1
       # INICIO DE MODIFICACIONES: Agregadas variables de entorno no sensibles
       environment-variables: |
         DB_NAME=${{ secrets.DB_NAME }}
         DB_USER=${{secrets.DB_USER}}
         DB_PASSWORD=${{secrets.DB_PASSWORD}}
         DB_PORT=${{secrets.DB_PORT}}
         DB_HOST=${{secrets.DB_HOST}}
         IMAGE_NAME=${{ secrets.ACR_NAME }}
         CONTAINER_NAME=${{ secrets.ACR_NAME }}
         IMAGE_TAG=${{ github.sha}}
         RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}
         LOCATION=${{ secrets.AZ_LOCATION }}
         ACR_NAME=${{ secrets.ACR_NAME }}
         PORT_CONTAINER=${{ secrets.PORT_CONTAINER }}
         SERVICE_PRINCIPAL_NAME=${{ secrets.SERVICE_PRINCIPAL_NAME }}
       # INICIO DE MODIFICACIONES: Agregada variable de entorno sensible
       secure-environment-variables: |
         CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
       # FIN DE MODIFICACIONES
   
   - name: Logout from Azure
     run: az logout

# NOTA: Nuevos secretos que necesitas agregar en GitHub:
# - DB_NAME
# - IMAGE_NAME
# - CONTAINER_NAME
# - IMAGE_TAG
# - LOCATION
# - ACR_NAME
# - PORT_CONTAINER
# - SERVICE_PRINCIPAL_NAME
# - CONNECTION_STRING